### ISSUE TITLE
JavaScript 02 __ JS + CSS Clock

### ISSUE THREAD

**Issue by Dcfm** [soyaine/JavaScript30#16]
一个小细节，谷歌浏览器的默认最小字号是 `12px`。该练习的 `CSS` 代码中根元素的字号设置的是 `10px`，代码中很多元素使用了 `rem` 单位，但实际尺寸是按根元素字号 `12px` 来渲染的。我开始对此疑惑不解，后来才搞明白。
应该将代码中的字号更改过来，或者添加注释。

**Comment by soyaine** [comment]
OK

**Comment by soyaine** [comment]
@Dcfm  最近一直没空维护代码，多谢
