### ISSUE TITLE
更新计划

### ISSUE THREAD

**Issue by soyaine** [soyaine/JavaScript30#17]
O__O "…
拖得太久了。必须搞起计划来完成更新了。

**Comment by yqwoshuai** [comment]
终于等到你，还好我没放弃，加油

**Comment by soyaine** [comment]
@yqwoshuai 多谢关注，我会思考计划后放在这里，欢迎监督。

**Comment by XieJing2016** [comment]
加油

**Comment by soyaine** [comment]
执行记录：
## 13 Slide in on Scroll
- 07-14 1h13m
- 07-17 1h58m
- 07-18 2h
共 5h11m
 ##

**Comment by soyaine** [comment]
开始写最后一篇的内容。
