### ISSUE TITLE
关于day20的speechRecognition接口的问题

### ISSUE THREAD

**Issue by dashnowords** [soyaine/JavaScript30#24]
参考API文档编写代码后，本地测试无效，搭建本地服务器后，onresult事件返回值是'network'字符串，网上给出的解释是语音识别需要远程发送至google的服务器处理后才能返回，所以在国内得不到正确的响应，由于最近VPN问题查的比较严，我也没能测试，不知道是否是由于这个原因造成的？

**Comment by soyaine** [comment]
我稍后看看，看是否能找到替代的办法。

**Comment by soyaine** [comment]
参考：
- http://www.zhangxinxu.com/wordpress/2017/01/html5-speech-recognition-synthesis-api/
- https://github.com/YIXUNFE/blog/issues/23
我在思考是否可以调用国内科大讯飞提供的接口。
