### ISSUE TITLE
下载链接

### ISSUE THREAD

**Issue by baixiaoji** [soyaine/JavaScript30#3]
官网最下面好像并没有提供百度云的下载链接，只有在课程界面才有。作者是找到了吗？

**Comment by baixiaoji** [comment]
抱歉，找到了没有认真开下面的FQA，随便帖一下https://pan.baidu.com/s/1nuN7tPJ#list/path=%2F

**Comment by uncleze2017** [comment]
官网的百度云连接已经失效了，你们有保存视频吗？ 给我发一份好吗？

**Comment by soyaine** [comment]
@uncleze2017 
我看了一下，是百度云那边把资源屏蔽了，分享之后都无法通过审核。
我再看看有没有其他办法。

**Comment by baixiaoji** [comment]
https://pan.baidu.com/s/1o8nt4Zw
@uncleze2017

**Comment by uncleze2017** [comment]
分享的还是失效了。。。

**Comment by uncleze2017** [comment]
百度账号 灬伪面灬

**Comment by soyaine** [comment]
@uncleze2017 发给你了。在「分享」的标签页里可以看到。

**Comment by uncleze2017** [comment]
@soyaine  收到了，谢谢啦

**Comment by jeffierw** [comment]
大佬能再发一份不？百度账号：梗槿@soyaine

**Comment by Artila** [comment]
同上，还可以分享吗？百度账号：绿茶离子@soyaine

**Comment by soyaine** [comment]
@jeffierw @Artila OK 请查收~

**Comment by ZerooreZ123** [comment]
@soyaine 能发一份给我嘛 百度云：风魂夜七章

**Comment by soyaine** [comment]
@ZerooreZ123 发啦

**Comment by soyaine** [comment]
有没有已经下载的同学可以试着压缩文件，重新分享一下？
我目前条件受限不方便下载。

在百度云已经尝试但无效的办法：
1. 分享空文件夹后把文件复制过去
2. 修改文件名
3. 分享单个文件
（以上几种都是分享后，访问链接后是 404）

**Comment by IMEAXX** [comment]
@soyaine 百度云资源不能用了，能麻烦帮我发一份链接吗？ 谢谢   百度云账号：我一只手捏死你

**Comment by jeffierw** [comment]
@IMEAXX   给你发了

**Comment by jeffierw** [comment]
压缩文件上传分享也被和谐。。

**Comment by discountry** [comment]
@soyaine 
求视频下载
百度账号 游神鱼
用私密方式分享应该可以正常显示

**Comment by soyaine** [comment]
@IMEAXX  发了~
@discountry 你设置了拒收好友分享……

**Comment by discountry** [comment]
@soyaine 不好意思，重新设置了，麻烦有空的时候再发一下，非常感谢。

**Comment by BoqiFeng** [comment]
百度云  id 冻冻冻果冻
发求资源～ 谢谢呢～

**Comment by soyaine** [comment]
### 关于视频文件的分享

1. 在此 issue 下留下你的百度云账号，注意不要设置为“拒收非好友消息”
2. 发送给你后我会将你带有账号信息的评论删除，不再一一 @
3. 一般每日早上和晚上会发送一次
4. 收到文件的小伙伴烦请帮忙找找分享文件的解决办法，造福大家

**Comment by yonjar** [comment]
百度帐号：遗忘之子op
十分感谢!

**Comment by soyaine** [comment]
新的资源链接：
链接: https://pan.baidu.com/s/1pK8GTNd 密码: dacy

**Comment by arronf2e** [comment]
给力，最近也在看这个，就是原网站的视频太慢太慢了，感谢

**Comment by elsieyin** [comment]
求分享，百度云帐号：yve120

**Comment by he1l0W0rld** [comment]
百度云账号：11131060  麻烦给百度云分享下视频资料 非常感谢

**Comment by HancockY** [comment]
百度云账号: 我叫尹晓龙
谢谢了~~

**Comment by LhsLz** [comment]
百度云账号:盖伦你无敌了
谢谢~

**Comment by ZavierTang** [comment]
百度云账号是：15616293680
可以发我一份吗？谢谢啦

**Comment by soyaine** [comment]
本 issue 不再提供视频，请自己动手。

**Comment by H246802** [comment]
不好意思晚来一步,我这边没找到,请问可以发我一份吗?  百度云账号是: 独辰潇叶
