### ISSUE TITLE
gogole浏览器中 设置currentTime

### ISSUE THREAD

**Issue by janwork** [soyaine/JavaScript30#31]
gogole浏览器中 设置currentTime

**Comment by soyaine** [comment]
请详细描述你的问题？

**Comment by janwork** [comment]
(*@ο@*) 哇～   就是在google浏览器中 我的currentTime 不能设置，一旦设置 currentTime 就等于 0 ；
百度之后，告知是 视频是本地的，必须上传服务器 服务器打开就可以 设置 currentTime值。
