### ISSUE TITLE
关于day1的练习小疑问。

### ISSUE THREAD

**Issue by Taco-Chan** [soyaine/JavaScript30#38]
function removeTransition(event) {
    if (event.propertyName !== 'transform') return; // 过滤其中一种事件
    event.target.classList.remove('playing'); // 移除高亮的样式
  }

这里判断 if (event.propertyName !== 'transform') return;   是什么意思？ 为什么要判断这个？没有这句判断貌似也是正常运行啊

**Comment by soyaine** [comment]
目的是只监听 transform 事件，仅在此类事件发生时进行处理，可以理解为减小消耗
