### ISSUE TITLE
14 JS中的引用与复制

### ISSUE THREAD

**Issue by imnaifu** [soyaine/JavaScript30#41]
Refer to your words 
> 最后需要注意的是：在前面的例子里面，我们用的数组和对象都只是一层嵌套，Lodash 有一个深度复制的方法，但你使用之前需要多考虑一下。

Actually, the JSON parse and stringify method, `const dev2 = JSON.parse(JSON.stringify(wes));`
is a kind of deep copy.

**Comment by soyaine** [comment]
Thank you. I have moved this sentence to the more appropriate position.
