### ISSUE TITLE
04 - Array Cardio Day 1 - readme:翻译问题

### ISSUE THREAD

**Issue by ghost** [soyaine/JavaScript30#51]
https://github.com/soyaine/JavaScript30/blob/master/04%20-%20Array%20Cardio%20Day%201/README.md

英文原文是Sort the inventors by birthdate, oldest to youngest，readme中翻译为“把他们按照年龄从大到小进行排序”，按照结果来看翻译为“把他们按照出生日期从大到小进行排序”是否更为准确？

**Comment by soyaine** [comment]
Fixed, Thanks.
