### ISSUE TITLE
目录 - 链接地址错误：03 CSS Variable-Guide链接地址错误

### ISSUE THREAD

**Issue by javaHashbrown** [soyaine/JavaScript30#53]
**03-CSS-Variable： Guide地址错误**  
  原因：地址里`Variable`前多了一个`%`

错误内容|详情
---|---
当前Guide地址|https://github.com/soyaine/JavaScript30/tree/master/03%20-%20CSS%20%Variables

正确内容|详情
---|---
正确Guide地址|https://github.com/soyaine/JavaScript30/tree/master/03%20-%20CSS%20Variables

**Comment by soyaine** [comment]
Thank you, fixed.
