### ISSUE TITLE
26-Stripe Follow Along Nav-文件夹名单词拼写错误，导致目录中对应链接错误

### ISSUE THREAD

**Issue by javaHashbrown** [soyaine/JavaScript30#54]
1.  错误描述  
repo的文件夹名拼写错误：`Stripe`-->`Strip` ，导致目录中Guide和Demo地址无法正确链接  

2.  修复方法  

项目|内容
---|---
当前文件夹名|26 - **Strip** Follow Along Nav
正确文件夹名|26 - **Stripe** Follow Along Nav

**Comment by soyaine** [comment]
Thank you. Fixed.
