### ISSUE TITLE
02 - JS + CSS Clock transition-timing-function并未用到

### ISSUE THREAD

**Issue by xiaolannuoyi** [soyaine/JavaScript30#56]
transition-timing-function: cubic-bezier(0.9, 0.54, 0.26, 1.68);  并未使用
使用的是这个
transition-timing-function：all 0.05s ease 0s

**Comment by soyaine** [comment]
麻烦展开一下？

**Comment by xiaolannuoyi** [comment]
方法一:

> if (secondDeg === 90) secHand.style.transition = 'all 0s';
  else secHand.style.transition = 'all 0.05s'; 

运行时为
![3](https://user-images.githubusercontent.com/21079721/49561491-922f2d80-f952-11e8-9a7c-22747d7cce20.png)

所以 你在css中设置的 transition-timing-function: cubic-bezier(0.9, 0.54, 0.26, 1.68); 并未使用,使用的是ease

应修改为
`else secHand.style.transition = 'all .05s cubic-bezier(0.9, 0.54, 0.26, 1.68)';`

**Comment by xiaolannuoyi** [comment]
@soyaine

**Comment by soyaine** [comment]
OK thank you.
