### ISSUE TITLE
01 JavaScript Drum Kit 事件名称拼写错误

### ISSUE THREAD

**Issue by nullx3** [soyaine/JavaScript30#57]
https://github.com/soyaine/JavaScript30/tree/master/01%20-%20JavaScript%20Drum%20Kit#%E5%A6%82%E4%BD%95%E4%BD%BF%E9%A1%B5%E9%9D%A2%E6%8C%89%E9%92%AE%E6%81%A2%E5%A4%8D%E5%8E%9F%E7%8A%B6

transitionend 错误拼写成transitionened

**Comment by soyaine** [comment]
Thank you. fixed
