### ISSUE TITLE
问一下，什么时候继续更新~

### ISSUE THREAD

**Issue by sunha1yang** [soyaine/JavaScript30#6]

**Comment by soyaine** [comment]
下周一

**Comment by cody1991** [comment]
开始看你这个的时候还在面试腾讯，现在已经拿到offer准备入职了😂

哈哈加油，又有更新了。虽然我已经看完英文版本的全部，不过还是会过来看看你的

**Comment by soyaine** [comment]
@cody1991 恭喜呀！我正在努力恢复重启中，还好还有人看。
