### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by kennyname** [soyaine/JavaScript30#8]
請問javascript30目前還有在更新嗎??真的寫得很不錯，新手參考獲得很大效益!!謝謝!

**Comment by Quinn-H** [comment]
应该会吧，她11天前最后一次commit

**Comment by soyaine** [comment]
很高興對你有幫助，會繼續更新，歡迎多多監督。

**Comment by soyaine** [comment]
最近也在更新，另外我新开了一个更新计划的 issue #17，所以这个先关闭啦。
